/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c Parse_jsb.ini" on 2013-12-25
* Script version: v0.6
*/
#import "jsb_config.h"
#if JSB_INCLUDE_PARSE


/*
 * PFObject
 */
#pragma mark - PFObject

#ifdef __cplusplus
extern "C" {
#endif

void JSB_PFObject_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_PFObject_object;
extern JSClass *JSB_PFObject_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_PFObject : JSB_NSObject
{
}
@end

/*
 * PFUser
 */
#pragma mark - PFUser

#ifdef __cplusplus
extern "C" {
#endif

void JSB_PFUser_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_PFUser_object;
extern JSClass *JSB_PFUser_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_PFUser : JSB_PFObject
{
}
@end

/*
 * PFGeoPoint
 */
#pragma mark - PFGeoPoint

#ifdef __cplusplus
extern "C" {
#endif

void JSB_PFGeoPoint_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_PFGeoPoint_object;
extern JSClass *JSB_PFGeoPoint_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_PFGeoPoint : JSB_NSObject
{
}
@end

/*
 * PFFile
 */
#pragma mark - PFFile

#ifdef __cplusplus
extern "C" {
#endif

void JSB_PFFile_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_PFFile_object;
extern JSClass *JSB_PFFile_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_PFFile : JSB_NSObject
{
}
@end
