/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soomla_cocos2dx_store_EventHandlerBridge */

#ifndef _Included_com_soomla_cocos2dx_store_EventHandlerBridge
#define _Included_com_soomla_cocos2dx_store_EventHandlerBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    billingSupported
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_billingSupported
  (JNIEnv *, jobject);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    billingNotSupported
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_billingNotSupported
  (JNIEnv *, jobject);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    closingStore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_closingStore
  (JNIEnv *, jobject);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    currencyBalanceChanged
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_currencyBalanceChanged
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    goodBalanceChanged
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_goodBalanceChanged
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    goodEquipped
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_goodEquipped
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    goodUnequipped
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_goodUnequipped
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    goodUpgrade
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_goodUpgrade
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    itemPurchased
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_itemPurchased
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    itemPurchaseStarted
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_itemPurchaseStarted
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    openingStore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_openingStore
  (JNIEnv *, jobject);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    playPurchaseCancelled
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_playPurchaseCancelled
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    playPurchase
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_playPurchase
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    playPurchaseStarted
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_playPurchaseStarted
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    playRefund
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_playRefund
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    restoreTransactions
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_restoreTransactions
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    restoreTransactionsStarted
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_restoreTransactionsStarted
  (JNIEnv *, jobject);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    unexpectedErrorInStore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_unexpectedErrorInStore
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
